# Generated by Django 5.1.1 on 2024-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_imgs'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_imgs'),
        ),
    ]
