# Generated by Django 5.1.1 on 2024-12-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_product_image_productgroup_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGroup',
            new_name='Category',
        ),
    ]
