# Generated by Django 5.1.1 on 2024-12-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_rename_productgroup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
