# Generated by Django 5.1.1 on 2025-02-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='category_imgs')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'homepage_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=255)),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='product_imgs')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'db_table': 'homepage_product',
            },
        ),
    ]
