# Generated by Django 5.1.1 on 2024-12-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_slug_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='homepage_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='homepage_product',
        ),
    ]
