# Generated by Django 5.1.1 on 2024-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_cart_user_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='homepage_cart',
        ),
    ]
