# Generated by Django 5.1.1 on 2025-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cart_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
